[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"

[font]
normal = { family = "ComicCode Nerd Font", style = "Regular" }
bold = { family = "ComicCode Nerd Font", style = "Bold" }
italic = { family = "ComicCode Nerd Font", style = "Italic" }
bold_italic = { family = "ComicCode Nerd Font", style = "Bold Italic" }
size = 15

[mouse]
hide_when_typing = true
